### PR TITLE
Add new API to enumerate available SocketCAN interfaces

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Comment by fpagliughi** [comment]
Wow, cool! I can actually use this in one of my new applications right now, and the implementation looks solid. 

I won't have time to test it until the weekend, at the earliest, but I will try to get it merged ASAP.
Thanks

**Comment by gmarull** [comment]
@fpagliughi gentle ping

**Comment by fpagliughi** [comment]
Yes, apologies, I'm overwhelmed at work this past month with two separate projects that need to be finished, and at the same time, every single one of my way-too-many open source projects got PRs that need to be tested and merged! I will get to this one ASAP. Hopefully this weekend.

**Review by fpagliughi — APPROVED** [review]
Appears to work well. Thanks!

**Pull request merged**
