### PR TITLE
Dump: handle extended IDs

### PR DESCRIPTION
**Pull request by mchodzikiewicz**
Set extended flag if ID is exceeding 11 bits

### CODE REVIEW

**Comment by mchodzikiewicz** [comment]
hey, I'd be very grateful for any feedback - I use this crate but I need extended ID working and I don't feel like maintaining my own fork :sweat_smile:

**Comment by fpagliughi** [comment]
Apologies, this is a big holiday week in the US, and last week was the crush of work everyone was trying to get done before the big holiday week. So I haven't had time for any open-source stuff. But if the PR test out OK, I'll merge it. And if it doesn't, I'll ask you to fix it, then merge it. :-)

But, yes, dump should support extended ID's.

**Comment by mchodzikiewicz** [comment]
Great to hear, sure thingo :) Sorry for rushing, I was just a tiny bit afraid that no one hangs here anymore

**Comment by XVilka** [comment]
Would be nice to have this merged, it's quite basic feature, IMHO.

**Comment by mchodzikiewicz** [comment]
@fpagliughi any updates?

**Comment by fpagliughi** [comment]
Apologies. I’ve been away on holiday much of the summer. I’ll be returning early Sept and getting back to some open source work shortly after.

**Review by fpagliughi — APPROVED** [review]
LGTM

**Pull request merged**
