### PR TITLE
Setup GH action based on actions-rs/meta template

### PR DESCRIPTION
**Pull request by marcelbuesing**
Basically a copy from [actions-rs/meta](https://github.com/actions-rs/meta) with adapted MSRV. I think it might make sense to add the [security-audit](https://github.com/actions-rs/meta/blob/master/recipes/security-audit.md) job as well in the future but I think that requires separate secret variable config in the repository.

### CODE REVIEW

**Comment by marcelbuesing** [comment]
Btw I think the build currently fails due to the netlink issue and formatting ..

**Comment by fpagliughi** [comment]
I definitely want to deploy this ASAP... but not until master is in a state that will pass, and I don't want to reformat the code until the older PR's are merged. No use making a mess before all the old code is gathered together.

**Comment by fpagliughi** [comment]
Should we remove `.travis.yml` when we merge this?

**Review by fpagliughi — APPROVED** [review]
LGTM

**Pull request merged**
