### PR TITLE
Support sending can frames over tokio canfd sockets (Resolves #57)

### LINKED ISSUE #57: Tokio-Async CanFd not capable of sending RemoteFrame?
I noticed that the Sync and async-io implementations of write_frame followed the CanAnyFrame usage pattern for the CanFdSocket, however the implementation in tokio.rs was only capable of sending CanFdFrames. Is there a reason for this API difference for Tokio vs async-io and sync?

Sync write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/socket.rs#L648

async-io write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/async_io.rs#L90

tokio write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/tokio.rs#L163

This is impacting a project where we are trying to send RemoteFrames over a CanFdSocket asynchronously using tokio. Do you have any information about this usecase?

### PR DESCRIPTION
**Pull request by EliteTK**
The first patch is unrelated and is just a cleanup of a bunch of extraneous path components. I couldn't compile without removing these first.

I think this is probably an acceptable solution. This also fixes #57.

Please let me know what you think. I can probably test this on real hardware soon but the new tests pass (although they currently seem to omit actually verifying that the received frame is of the right type and content etc).

### CODE REVIEW

**Comment by EliteTK** [comment]
Actually, looks like #68 already addresses the unnecessary path component issue and #61 addresses the panic. Feel free to just merge those first. #67 would clash with this change but I don't mind re-doing it if you were to apply it first.

Technically with #67 it's possible to also make write_frame take a `&` like the equivalents in the other async implementations, but it would also mean a more obviously breaking change (I'm not sure if this is considered breaking as it is, technically no callers should be affected).

Anyway, let me know, this isn't particularly urgent right now.

**Comment by EliteTK** [comment]
I've actually gone ahead and rebased things on top of the other PRs.

Applying this (which is now breaking) will also include #68, #61, and #67 (the authorship information is preserved so while the PRs won't get auto-closed as merged, the contributors aren't being stiffed).

But feel free to just apply those PRs individually prior to this one.

I just did this so I could develop on top of #67 and didn't step on #68 and #61's toes.

I've also added a fix for the Stream impl as well as even more tests.

**Comment by EliteTK** [comment]
I've now rebased against all the accepted PRs and force pushed the new version of my commit.

**Comment by fpagliughi** [comment]
Nice!
I'm just arriving back from summer holiday and will start testing the stuff I recently merged on some real equipment. Then I will look to test and merge this before doing anything else. You've already had to rebase a couple times!

**Comment by EliteTK** [comment]
> You've already had to rebase a couple times!

Ah, don't worry about that. I don't mind it.

**Comment by martinjaeger** [comment]
I came across the same issue with the tokio API and tested out this PR.

It works very well (thanks @EliteTK). Would really appreciate getting it merged and officially released.

**Comment by fpagliughi** [comment]
Yes, apologies. A new release is overdue. I'm at RustConf this week, but will get a few of these PRs landed and tested when I return, and publish a new version.

**Comment by showier-drastic** [comment]
Just a friendly ping on this PR, which is needed to send CAN frames on CAN-FD interfaces.

**Review by fpagliughi — APPROVED** [review]
Thanks! Sorry for the delay

**Pull request merged**
